#!/usr/bin/perl
use strict;
use warnings;

my @anarciOutput = <STDIN>;
pop @anarciOutput;
my $anarciOutput = join('', @anarciOutput);
$anarciOutput =~ s/^#.*\n//mg;
my @modifiedOutput; 
for my $line (split("\n", $anarciOutput))
{
	#$1 seq type $2 aminoacid number $3 insertion code $4 aminoacid name
	$line =~/(H|L)\s+(\d+)\s+([A-Z])?\s([A-Z-])/;
	if(defined $3)
	{
		push @modifiedOutput, $4 .  "\t" . $2 ." " . lc($3) . "\t\n";
	}
	else
	{
		push @modifiedOutput, $4 . "\t" . $2 . "\t\n";
	}
}

my $n = scalar @modifiedOutput;
for my $i ( 3 .. $n-4 )
{
    print $modifiedOutput[$i];
}
