# Directories
CURRENT_DIR = .
SCRIPTS = ${CURRENT_DIR}/scripts
DATA = ${CURRENT_DIR}/data
LOGS = ${CURRENT_DIR}/logs
SCRIPTS_OUT = ${CURRENT_DIR}/scripts_out
HEAVY_LIGHT = ${SCRIPTS_OUT}/heavy_and_light_chains
HEAVY_LIGHT_ID = ${HEAVY_LIGHT}/id
HEAVY_LIGHT_FASTA = ${HEAVY_LIGHT}/fasta
HEAVY_LIGHT_ALIGMENTS = ${HEAVY_LIGHT}/aligments
HEAVY_LIGHT_COMPARE = ${HEAVY_LIGHT}/pdb_clusters_compare

# Output files's extensions
CLUSTER = clstr
IDS_FILE = txt
PDB = pdb
GZ = gz
FASTA = fasta

# Scripts
PDB_DOWNLOAD = ${SCRIPTS}/byLinkDownload
READ_FRAGMENT = ${SCRIPTS}/read_fragment
READ_CLUSTER = ${SCRIPTS}/readCluster
MAKE_FASTA =${SCRIPTS}/makeFasta
COMPARE_NUMBERING= ${SCRIPTS}/compareNumberingPdbCluster
ALIGNER = muscle

# Files
SORTED_IDS_FILE = ${SCRIPTS_OUT}/sorted_ids.${IDS_FILE}
DATA_FILE_NAMES = $(addsuffix .${PDB}.${GZ}, $(shell cat ${SORTED_IDS_FILE}))
DATA_FILES = $(addprefix ${DATA}/, ${DATA_FILE_NAMES})
LIGHT_CHAINS_ID = ${HEAVY_LIGHT_ID}/light_chains.${IDS_FILE}
HEAVY_CHAINS_ID = ${HEAVY_LIGHT_ID}/heavy_chains.${IDS_FILE}
HEAVY_CHAINS_FASTA = ${HEAVY_LIGHT_FASTA}/heavy_chains.${FASTA}
LIGHT_CHAINS_FASTA = ${HEAVY_LIGHT_FASTA}/light_chains.${FASTA}
HEAVY_CHAINS_FASTA_CLUSTERS = ${HEAVY_LIGHT_FASTA}/heavy_chainsClustered.${FASTA}
LIGHT_CHAINS_FASTA_CLUSTERS = ${HEAVY_LIGHT_FASTA}/light_chainsClustered.${FASTA}
HEAVY_CHAINS_CLUSTERS = ${HEAVY_LIGHT_FASTA}/heavy_chainsClustered.${FASTA}.${CLUSTER}
LIGHT_CHAINS_CLUSTERS = ${HEAVY_LIGHT_FASTA}/light_chainsClustered.${FASTA}.${CLUSTER}
CLUSTERS_FOR_ALIGMENT = $(shell ls ${HEAVY_LIGHT_ALIGMENTS})
CLUSTERS_COMPARE_NAMES = $(addsuffix .out,$(CLUSTERS_FOR_ALIGMENT))
CLUSTERS_COMPARE = $(addprefix ${HEAVY_LIGHT_COMPARE}/,$(CLUSTERS_COMPARE_NAMES))

# Link
PDB_LINK = http://www.rcsb.org/pdb/files


all: ${CLUSTERS_COMPARE}

${HEAVY_LIGHT_COMPARE}/%.afa.out: ${HEAVY_LIGHT_ALIGMENTS}/%.afa
	./${COMPARE_NUMBERING} $< ${DATA} ${HEAVY_LIGHT_COMPARE}

${CLUSTERS_FOR_ALIGMENT}: regenerateClusters

regenerateClusters: ${LIGHT_CHAINS_FASTA_CLUSTERS} ${HEAVY_CHAINS_FASTA_CLUSTERS} ${LIGHT_CHAINS_FASTA} ${HEAVY_CHAINS_FASTA}
	./${READ_CLUSTER} ${LIGHT_CHAINS_FASTA} ${LIGHT_CHAINS_CLUSTERS} ${HEAVY_LIGHT_ALIGMENTS} "light"
	./${READ_CLUSTER} ${HEAVY_CHAINS_FASTA} ${HEAVY_CHAINS_CLUSTERS} ${HEAVY_LIGHT_ALIGMENTS} "heavy"

${LIGHT_CHAINS_FASTA_CLUSTERS}: ${LIGHT_CHAINS_FASTA}
	cd-hit -i $< -o $@

${HEAVY_CHAINS_FASTA_CLUSTERS}: ${HEAVY_CHAINS_FASTA}
	cd-hit -i $< -o $@

${HEAVY_CHAINS_FASTA}: ${HEAVY_CHAINS_ID}
	./${MAKE_FASTA} $@ $< ${DATA}

${LIGHT_CHAINS_FASTA}: ${LIGHT_CHAINS_ID}
	./${MAKE_FASTA} $@ $< ${DATA}

${HEAVY_CHAINS_ID} ${LIGHT_CHAINS_ID}: ${DATA_FILES}
	./${READ_FRAGMENT} ${DATA} ${HEAVY_LIGHT_ID}

${DATA}/%.${PDB}.${GZ}: 
	./${PDB_DOWNLOAD} ${DATA} ${LOGS} ${PDB_LINK} $(notdir $@)
	

