# Directories
## Essentail directories
CURRENT_DIR = .
SCRIPTS = ${CURRENT_DIR}/scripts
DATA = ${CURRENT_DIR}/data
LOGS = ${CURRENT_DIR}/logs
SCRIPTS_OUT = ${CURRENT_DIR}/scripts_out

## Antybody seq analize directories
HEAVY_LIGHT = ${SCRIPTS_OUT}/heavy_light_chains
HEAVY_LIGHT_ID = ${HEAVY_LIGHT}/id
HEAVY_LIGHT_FASTA = ${HEAVY_LIGHT}/fasta
HEAVY_LIGHT_ALIGMENTS = ${HEAVY_LIGHT}/aligments
HEAVY_LIGHT_COMPARE = ${HEAVY_LIGHT}/compare
SEQ_BY_SCHEME = ${SCRIPTS_OUT}/seq_by_numbering_scheme
ID_BY_SCHEME = ${SEQ_BY_SCHEME}/id
FASTA_BY_SCHEME = ${SEQ_BY_SCHEME}/fasta
ALIGMENT_BY_SCHEME = ${SEQ_BY_SCHEME}/aligments
CD_HIT_BY_SCHEME = ${SEQ_BY_SCHEME}/cd-hit_out
CLUSTERS_COMPARE_BY_SCHEME = ${SEQ_BY_SCHEME}/pdb_cluster_compare
TRIMMED_BY_SCHEME = ${SEQ_BY_SCHEME}/trimmedNumbering
CLUSTERS_BY_SCHEME = ${SEQ_BY_SCHEME}/clusters_align
NUMBERING_COMPARE= ${SEQ_BY_SCHEME}/numbering_compare
TRIMMED_BY_SCHEME_CLUSTERS:=${SEQ_BY_SCHEME}/trimmedNumbering_clusters
HMM_BY_SCHEME_CLUSTERS:=${SEQ_BY_SCHEME}/hmms_clusters
GENERATED_BY_SCHEME_CLUSTERS:=${SEQ_BY_SCHEME}/hmmemit_generated_seq
SCORE_BY_SCHEME_CLUSTERS:=${SEQ_BY_SCHEME}/hmmsearch_scores_files
## Id sort directories #
PFAM_DIR = PfamScan
PFAM_SCAN_DATA = pfam_data

# Output files's extensions #
## Essential extensions ##
IDS_FILE = id
PDB = pdb
GZ = gz

## Antybody seq analize extensions ##
CLUSTER = clstr
FASTA = fasta
PFAM_OUT = out
# Scripts #
## Antybody seq analize scripts ##
READ_FRAGMENT = ${SCRIPTS}/read_fragment
READ_CLUSTER = ${SCRIPTS}/readCluster
MAKE_FASTA =${SCRIPTS}/makeFasta
COMPARE_NUMBERING= ${SCRIPTS}/compareNumberingPdbCluster
ALIGNER = mafft
EXCLUDE_FILE = ${SCRIPTS}/excludeNoNNumbering
CUT_NUMBERING = ${SCRIPTS}/cutNumbering
## Id sort scripts ##
EXTRACT = ${SCRIPTS}/extractEnCluster
ID_FILTER = ${SCRIPTS}/idFilter
PFAM_SCAN = ${PFAM_DIR}/pfam_scan.pl
DOWNLOAD_FILE = ${SCRIPTS}/byLinkDownload
TRIM_EXTACTED = ${SCRIPTS}/trimExtracted
IDENTIFY_SCHEME = ${SCRIPTS}/identifyScheme
SORT_BY_SCHEME = ${SCRIPTS}/sortByScheme
GREP_MOST_PROBABLE = ${SCRIPTS}/grepMostProbableSeq
# Files #
## Id sort files ##
PDB_SEQ_FILE = pdb_seqres.txt.gz
PDB_ID_FILE = rcsb_pdb_ids_20240228040928.txt
PFAM_DATA_FILES := $(addprefix $(PFAM_SCAN_DATA)/, Pfam-A.hmm.h3i Pfam-A.hmm.h3p Pfam-A.hmm.h3f Pfam-A.hmm.h3m)
ACTIVE_SITE_NAME = active_site.dat
ACTIVE_SITE := $(PFAM_SCAN_DATA)/${ACTIVE_SITE_NAME}
HMM_NAME := Pfam-A.hmm
HMM := $(PFAM_SCAN_DATA)/${HMM_NAME}
HMM_DAT_NAME := Pfam-A.hmm.dat
HMM_DAT := $(PFAM_SCAN_DATA)/${HMM_DAT_NAME}
EXTRACTED_FASTA = ${SCRIPTS_OUT}/extracted.${FASTA}
TRIMMED_FASTA = ${SCRIPTS_OUT}/extractedTrimmed.${FASTA}
PFAM_SCAN_OUTPUT = ${SCRIPTS_OUT}/pfam_scan.${PFAM_OUT}
SORTED_IDS_FILE = ${SCRIPTS_OUT}/sorted_ids.${IDS_FILE}
## Antybody seq analize files ##
LIGHT_CHAINS_ALIGNMENT = ${HEAVY_LIGHT_ALIGMENTS}/light_alignment.afa
HEAVY_CHAINS_ALIGNMENT = ${HEAVY_LIGHT_ALIGMENTS}/heavy_alignment.afa
LIGHT_CHAINS_ALIGNMENT_COMPARE = ${HEAVY_LIGHT_COMPARE}/light_alignment.tsv
HEAVY_CHAINS_ALIGNMENT_COMPARE = ${HEAVY_LIGHT_COMPARE}/heavy_alignment.tsv
IDS_WITH_NUMBERING_LIGHT = ${HEAVY_LIGHT_ID}/light_chainsWithNumbering.${IDS_FILE}
IDS_WITH_NUMBERING_HEAVY = ${HEAVY_LIGHT_ID}/heavy_chainsWithNumbering.${IDS_FILE}
DATA_FILE_NAMES = $(addsuffix .${PDB}.${GZ}, $(shell cat ${SORTED_IDS_FILE}))
DATA_FILES = $(addprefix ${DATA}/, ${DATA_FILE_NAMES})
LIGHT_CHAINS_ID = ${HEAVY_LIGHT_ID}/light_chains.${IDS_FILE}
HEAVY_CHAINS_ID = ${HEAVY_LIGHT_ID}/heavy_chains.${IDS_FILE}
HEAVY_CHAINS_FASTA = ${HEAVY_LIGHT_FASTA}/heavy_chains.${FASTA}
LIGHT_CHAINS_FASTA = ${HEAVY_LIGHT_FASTA}/light_chains.${FASTA}
L_KABAT_ID = ${ID_BY_SCHEME}/L_Kabat.${IDS_FILE}
H_KABAT_ID = ${ID_BY_SCHEME}/H_Kabat.${IDS_FILE}
L_CHOTIA_ID = ${ID_BY_SCHEME}/L_Chothia.${IDS_FILE}
H_CHOTIA_ID = ${ID_BY_SCHEME}/H_Chothia.${IDS_FILE}
L_KABAT_CHOTIA_ID = ${ID_BY_SCHEME}/L_Kabat_Chothia.${IDS_FILE}
H_KABAT_CHOTIA_ID = ${ID_BY_SCHEME}/H_Kabat_Chothia.${IDS_FILE}
L_MARTIN_CHOTIA_ID = ${ID_BY_SCHEME}/L_Martin_Chothia.${IDS_FILE}
H_MARTIN_CHOTIA_ID = ${ID_BY_SCHEME}/H_Martin_Chothia.${IDS_FILE}
ID_FILES := ${H_KABAT_CHOTIA_ID} ${L_KABAT_CHOTIA_ID} ${H_CHOTIA_ID} ${H_CHOTIA_ID} ${H_KABAT_ID} ${L_KABAT_ID} ${H_MARTIN_CHOTIA_ID} ${L_MARTIN_CHOTIA_ID}
FASTA_FILES := $(patsubst ${ID_BY_SCHEME}/%.id, ${FASTA_BY_SCHEME}/%.fasta, ${ID_FILES})
ALIGMENTS_FILES := $(patsubst ${ID_BY_SCHEME}/%.id, ${ALIGMENT_BY_SCHEME}/%.afa, ${ID_FILES})
COMPARE_FILES := $(patsubst ${ID_BY_SCHEME}/%.id, ${NUMBERING_COMPARE}/%.tsv, ${ID_FILES})
TRIMMED_FILES := $(patsubst ${ID_BY_SCHEME}/%.id, ${TRIMMED_BY_SCHEME}/%.tsv, ${ID_FILES})
L_KABAT_CHOTIA_FASTA_CLUSTERS = ${CD_HIT_BY_SCHEME}/L_Kabat_Chothia_Clustered.${FASTA}
H_KABAT_CHOTIA_FASTA_CLUSTERS = ${CD_HIT_BY_SCHEME}/H_Kabat_Chothia_Clustered.${FASTA}
CLUSTERED_FILES := ${L_KABAT_CHOTIA_FASTA_CLUSTERS} ${H_KABAT_CHOTIA_FASTA_CLUSTERS}
ALIGNED_CLUSTERS_NAMES := $(shell ls ${CLUSTERS_BY_SCHEME})
ALIGNED_CLUSTERS := $(addprefix ${CLUSTERS_BY_SCHEME}/, ${ALIGNED_CLUSTERS_NAMES})
COMPARED_CLUSTERS := $(patsubst ${CLUSTERS_BY_SCHEME}/%.afa, ${CLUSTERS_COMPARE_BY_SCHEME}/%.tsv, ${ALIGNED_CLUSTERS})
TRIMMED_CLUSTERS := $(patsubst ${CLUSTERS_BY_SCHEME}/%.afa, ${TRIMMED_BY_SCHEME_CLUSTERS}/%.tsv, ${ALIGNED_CLUSTERS})
HMMS_CLUSTERS := $(patsubst ${CLUSTERS_BY_SCHEME}/%.afa, ${HMM_BY_SCHEME_CLUSTERS}/%.hmm, ${ALIGNED_CLUSTERS})
# Links
PDB_LINK = http://www.rcsb.org/pdb/files
SEQ_FROM_PDB_LINK = https://files.wwpdb.org/pub/pdb/derived_data
PFAM_DATA_LINK = https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release

.PRECIOUS: ${CLUSTERS_COMPARE_BY_SCHEME}/%.tsv ${GENERATED_BY_SCHEME_CLUSTERS}/%.fasta ${HMM_BY_SCHEME_CLUSTERS}/%.hmm ${ALIGMENT_BY_SCHEME}/%.afa ${FASTA_BY_SCHEME}/%.fasta

all: ${TRIMMED_CLUSTERS} ${TRIMMED_FILES} ${COMPARE_FILES} ${HMMS_CLUSTERS}
	
## Antybody seq analize

${HMM_BY_SCHEME_CLUSTERS}/%.hmm:  ${CLUSTERS_BY_SCHEME}/%.afa
	hmmbuild $@ $<
	
${TRIMMED_BY_SCHEME_CLUSTERS}/%.tsv: ${CLUSTERS_COMPARE_BY_SCHEME}/%.tsv
	./${CUT_NUMBERING} $< ${TRIMMED_BY_SCHEME_CLUSTERS}

${CLUSTERS_COMPARE_BY_SCHEME}/%.tsv: ${CLUSTERS_BY_SCHEME}/%.afa
	./${COMPARE_NUMBERING} $< ${DATA} ${CLUSTERS_COMPARE_BY_SCHEME}

${ALIGNEED_CLUSTERS}: regenerateClusters

regenerateClusters: ${CLUSTERED_FILES} ${FASTA_BY_SCHEME}/L_Kabat_Chothia.fasta ${FASTA_BY_SCHEME}/H_Kabat_Chothia.fasta
	./${READ_CLUSTER} ${FASTA_BY_SCHEME}/L_Kabat_Chothia.fasta ${L_KABAT_CHOTIA_FASTA_CLUSTERS}.${CLUSTER} ${CLUSTERS_BY_SCHEME} "light"
	./${READ_CLUSTER} ${FASTA_BY_SCHEME}/H_Kabat_Chothia.fasta ${H_KABAT_CHOTIA_FASTA_CLUSTERS}.${CLUSTER} ${CLUSTERS_BY_SCHEME} "heavy"

${H_KABAT_CHOTIA_FASTA_CLUSTERS}: ${FASTA_BY_SCHEME}/H_Kabat_Chothia.fasta
	cd-hit -i  $< -o $@

${L_KABAT_CHOTIA_FASTA_CLUSTERS}: ${FASTA_BY_SCHEME}/L_Kabat_Chothia.fasta
	cd-hit -i $< -o $@


${TRIMMED_BY_SCHEME}/%.tsv: ${NUMBERING_COMPARE}/%.tsv
	./${CUT_NUMBERING} $< ${TRIMMED_BY_SCHEME}

${NUMBERING_COMPARE}/%.tsv: ${ALIGMENT_BY_SCHEME}/%.afa
	./${COMPARE_NUMBERING} $< ${DATA} ${NUMBERING_COMPARE}

${ALIGMENT_BY_SCHEME}/%.afa: ${FASTA_BY_SCHEME}/%.fasta
	${ALIGNER} --op 10 --ep 1 $< > $@
	
${FASTA_BY_SCHEME}/%.fasta: ${ID_BY_SCHEME}/%.id
	./${MAKE_FASTA} $@ $< ${DATA}


${H_KABAT_ID} ${H_CHOTIA_ID} ${H_KABAT_CHOTIA_ID} ${H_MARTIN_CHOTIA_ID}: ${HEAVY_CHAINS_ALIGNMENT_COMPARE}
	./${IDENTIFY_SCHEME} ${HEAVY_CHAINS_ALIGNMENT_COMPARE} > "file.tmp"
	./${SORT_BY_SCHEME} ${ID_BY_SCHEME} 'H' "file.tmp"
	rm "file.tmp"

${L_KABAT_ID} ${L_CHOTIA_ID} ${L_KABAT_CHOTIA_ID} ${L_MARTIN_CHOTIA_ID}: ${LIGHT_CHAINS_ALIGNMENT_COMPARE}
	./${IDENTIFY_SCHEME} ${LIGHT_CHAINS_ALIGNMENT_COMPARE} > "file.tmp"
	./${SORT_BY_SCHEME} ${ID_BY_SCHEME} 'L' "file.tmp"
	rm "file.tmp"

${LIGHT_CHAINS_ALIGNMENT_COMPARE}: ${LIGHT_CHAINS_ALIGNMENT}
	./${COMPARE_NUMBERING} $< ${DATA} ${HEAVY_LIGHT_COMPARE}
	
${HEAVY_CHAINS_ALIGNMENT_COMPARE}: ${HEAVY_CHAINS_ALIGNMENT}
	./${COMPARE_NUMBERING} $< ${DATA} ${HEAVY_LIGHT_COMPARE}
	
${HEAVY_CHAINS_ALIGNMENT}: ${HEAVY_CHAINS_FASTA}
	${ALIGNER} --op 10 --ep 1 $< > $@


${LIGHT_CHAINS_ALIGNMENT}: ${LIGHT_CHAINS_FASTA}
	${ALIGNER} --op 10 --ep 1 $< > $@
	
${HEAVY_CHAINS_FASTA}: ${IDS_WITH_NUMBERING_HEAVY}
	./${MAKE_FASTA} $@ $< ${DATA}

${LIGHT_CHAINS_FASTA}: ${IDS_WITH_NUMBERING_LIGHT}
	./${MAKE_FASTA} $@ $< ${DATA}

${IDS_WITH_NUMBERING_LIGHT}: ${DATA_FILES} ${LIGHT_CHAINS_ID}
	./${EXCLUDE_FILE} ${DATA} ${HEAVY_LIGHT_ID} ${LIGHT_CHAINS_ID}

${IDS_WITH_NUMBERING_HEAVY}: ${DATA_FILES} ${HEAVY_CHAINS_ID}
	./${EXCLUDE_FILE} ${DATA} ${HEAVY_LIGHT_ID} ${HEAVY_CHAINS_ID}

${HEAVY_CHAINS_ID} ${LIGHT_CHAINS_ID}: ${SORTED_IDS_FILE}
	./${READ_FRAGMENT} ${DATA} ${HEAVY_LIGHT_ID}

${DATA}/%.${PDB}.${GZ}: 
	./${DOWNLOAD_FILE} ${DATA} ${LOGS} ${PDB_LINK} $(notdir $@)
	

## Id sort
update_id_file: ${SORTED_IDS_FILE}

${SORTED_IDS_FILE}: ${PFAM_SCAN_OUTPUT}
	./${ID_FILTER} ${PDB_ID_FILE} $< $@

${PFAM_SCAN_OUTPUT}: ${TRIMMED_FASTA} ${PFAM_DATA_FILES}
	${PFAM_SCAN} -fasta $< -dir ${PFAM_SCAN_DATA} -outfile $@

${TRIMMED_FASTA}: ${EXTRACTED_FASTA}
	./${TRIM_EXTACTED} $< $@

${EXTRACTED_FASTA}: ${PDB_SEQ_FILE} ${PDB_ID_FILE}
	./${EXTRACT} ${PDB_ID_FILE} ${PDB_SEQ_FILE} $@

${PDB_SEQ_FILE}:
	./${DOWNLOAD_FILE} ${CURRENT_DIR} ${CURRENT_DIR} ${SEQ_FROM_PDB_LINK} $(@F)
	
${PFAM_DATA_FILES}: ${ACTIVE_SITE} ${HMM} ${HMM_DAT}
	hmmpress ${HMM}

${ACTIVE_SITE}:
	./${DOWNLOAD_FILE} ${PFAM_SCAN_DATA} ${PFAM_SCAN_DATA} ${PFAM_DATA_LINK} ${ACTIVE_SITE_NAME}.${GZ}
	gunzip ${ACTIVE_SITE}.${GZ}

${HMM}:
	./${DOWNLOAD_FILE} ${PFAM_SCAN_DATA} ${PFAM_SCAN_DATA} ${PFAM_DATA_LINK} ${HMM_NAME}.${GZ}
	gunzip ${HMM}.${GZ}

${HMM_DAT}:
	./${DOWNLOAD_FILE} ${PFAM_SCAN_DATA} ${PFAM_SCAN_DATA} ${PFAM_DATA_LINK} ${HMM_DAT_NAME}.${GZ}
	gunzip ${HMM_DAT}.${GZ}



