#!/bin/bash

outfile=$1

if [ -z "$outfile" ]; then
  echo "Error: Please provide an output file as the first argument."
  exit 1
fi


> "$outfile"
for gene_id in 28483 28481 28479 28477 28476 28475; do
  echo "Fetching protein for gene ID: $gene_id"
  elink -db gene -id $gene_id -target protein | efetch -format fasta >> "$outfile"
done


