#!/usr/bin/perl
use strict;
use warnings;

my @anarciOutput = <STDIN>;
pop @anarciOutput;
my $anarciOutput = join('', @anarciOutput);
$anarciOutput =~ s/^#.*\n//mg;
my @modifiedOutput; 
for my $line (split("\n", $anarciOutput))
{
	#$1 seq type $2 aminoacid number $4 insertion code $5 aminoacid name
	$line =~/(H|L)\s+(\d+)\s+(([A-Z])?\s([A-Z-]))/;
	if(defined $4)
	{
		push @modifiedOutput, $5 .  "\t" . $2 . $4 . "\n";
	}
	else
	{
		push @modifiedOutput, $5 . "\t" . $2 . "\n";
	}
}

print "#length: " .  scalar(@modifiedOutput) . "\n";
for my $line (@modifiedOutput)
{
	print $line;
}
