#!/usr/bin/perl
use strict;
use warnings;

my $fastaFileName = $ARGV[0];
my $outDir = $ARGV[1];
open my $fh, '<', $fastaFileName or die "Could not open file: $!";

$/ = "\n>";
my $fastaNumber = 0;
while(my $fasta = <$fh>)
{
	my $output_file = "$outDir/fasta$fastaNumber.fasta";
	open(my $out, '>', $output_file) or die "Could not open file '$output_file': $!";
	
	chomp($fasta);
	my @lines = split("\n", $fasta);
    	my $header = shift @lines;
	my $sequence = join("", @lines);
	print $out ">$header\n$sequence\n";
	
    	close($out);
    	$fastaNumber++;
}

close($fh);
