#!/bin/bash

fastaFile=${1}
idsInCluster=${2}
clusterName=${3}
outDir=${4}

fasta=''
touch tmp.fasta
for seq in $idsInCluster
do
	grep -A 1 "^>$seq" $fastaFile >> tmp.fasta
done
muscle -align tmp.fasta -output "$outDir/aligned$clusterName.afa"
rm tmp.fasta

