#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;
		
my $clusterFile = $ARGV[0];
my $dataDir = $ARGV[1];
my $out_dir = $ARGV[2];
my $clusterFileName = basename($clusterFile);
open(my $cluster_handler,'<', $clusterFile)
	or die " Could not open file: '$clusterFile' $!";

my @seq;
my $index=-1;
while(my $line = <$cluster_handler>)
{
	chomp($line);
	if($line =~ /^>(.+)_([A-Z])/)
	{
		$index++;
		$seq[$index] =
				{
					pdb_id => $1,
					chain => $2
				};
		next;	
	}
	$seq[$index] -> {seq} .= $line;
}

my $currentAminoNumber='start';


foreach my $entry (@seq)
{
	my @pdb_numbering;
	my $pdb_ATOM = qx(zcat $dataDir/$entry->{pdb_id}.pdb.gz | pdb_chain -c $entry->{chain} | grep "^ATOM");
   	my @ATOMS = split /\n/, $pdb_ATOM;
   	foreach my $atom (@ATOMS)
   	{
   		$atom =~ /^ATOM\s+[0-9]+\s+[A-Z0-9]+\s*([A-Z]+)\s+$entry->{chain}\s*(-?[0-9]+[A-Z]*).+/;
   		#print $entry->{pdb_id} . $2 . " ";
   		next if $currentAminoNumber eq $2;
   		$currentAminoNumber = $2;
   		push @pdb_numbering, $currentAminoNumber;
   	}
	$currentAminoNumber='start';
  	$entry->{pdb_numbering}=\@pdb_numbering;
}

open(my $out_handler, '>', "$out_dir/$clusterFileName.out" )
	or die "Could not open file '$out_dir/$clusterFileName.out' $!";
foreach my $entry (@seq)
{
	my $index=0;
	my $seq_id = "$entry->{pdb_id}_$entry->{chain}";
	my $offset = length($seq_id);
	my @output;
	$output[0] = $seq_id;
	for (my $i = 0; $i < $offset; $i++)
	{
	    $output[1] .= " ";
	}
	foreach my $char (split('',$entry->{seq}))
	{
		$output[0] .= " $char";
		if($char eq '-')
		{
			$output[1] .= " -";
		}
		else
		{
			$output[1] .= " $entry->{pdb_numbering}[$index]";
			$index++;
		}
	}
	#print $output[0]. "\n";
	print $out_handler $output[0] . "\n";
	print $out_handler $output[1] . "\n\n";
}


close($cluster_handler);
close($out_handler);
