#!/usr/bin/sh

ID_FILE=${1}
OUTDIR=${2}
LOGDIR=${3}
FILE_EXTENSION=${4}
FILE_LINK="http://www.rcsb.org/pdb/files"

for id in $(cat $ID_FILE)
do
	FILE_NAME="$id.$FILE_EXTENSION"
	(set -x; directory-metadata; wget -O "$OUTDIR/$FILE_NAME" "$FILE_LINK/$FILE_NAME"; date -Imin) 2>&1 | tee "$LOGDIR/$FILE_NAME.log"
done
