#!/usr/bin/perl

use strict;
use warnings;
use IO::Uncompress::Gunzip;
use File::Basename;
my $data_dir = $ARGV[0];
my $out_dir = $ARGV[1];
my $id_file = $ARGV[2];
open(my $id_handler, '<', $id_file )
	or die "Could not open file $id_file $!";
my %files;
while(my $id =<$id_handler>)
{
	$id =~/(.{4})_(.)/;
	$files{"$1"} = $2;
}
my @foundNumbering;
my @noNumbering;
foreach my $pdbFile (keys %files)
{
	my $pdb_handler = IO::Uncompress::Gunzip->new("$data_dir/$pdbFile.pdb.gz")
			or die "Can't open $data_dir/$pdbFile.pdb.gz\n";
	my $chain_name = $files{$pdbFile};
	print "$pdbFile is proccesing\n";
	while(my $line =<$pdb_handler>)
	{
		next if $line !~ /^ATOM/;
		if($line =~/.{21}$chain_name.{4}[A-Z].{53}/)
		{
			my $pdb_with_chain = $pdbFile . "_$chain_name";
			push @foundNumbering, $pdb_with_chain; 
			last;
		}
	}
	close $pdb_handler;
}
my $filename = basename($id_file);
$filename =~ s/\..*//;
$filename .= "WithNumbering";
open(my $found_handler, '>', "$out_dir/$filename.id" )
	or die "Could not open file '$out_dir/$filename.id' $!";

$, = "\n";
print $found_handler @foundNumbering;

close($found_handler);
