#!/bin/bash

idsFileName=${1}
seqFileName=${2}
outputFileName=${3}

# This script extracts sequences corresponding to IDs from the ID file and
# writes them to a separate file. Then it clusters the file and
# generates two files: a file with clusters and a clustered FASTA file.

# Usage -------------------------------------\
# ${0} idFile seqFile outputDir              \
#--------------------------------------------\

file_type=$(file -b "$seqFileName")

if [[ ! $file_type == *gzip* ]]
then
	echo "Sequence file has to be gzipped" 1>&2
	exit 1
fi


IFS=', ' read -ra id_array < "$idsFileName"

touch ${outputFileName}
for id in "${id_array[@]}"
do
	echo "$id is currently processing"
	id=$(echo "$id" | tr '[:upper:]' '[:lower:]')
	zcat $seqFileName | grep -A 1 $id >> ${outputFileName}
done
sed -i '/^--$/d' ${outputFileName}
echo "All sequences have been successfully extracted from file"
echo "Starting clustering"
cd_hit_out=$(basename $outputFileName .fasta)
cd-hit -i ${outputFileName} -c 1 -o "${cd_hit_out}Clustered.fasta"
