#!/usr/bin/sh

# This script downloads a files from the FTP archive
# and also creates a download log. Both files are saved at the specified path.

# Usage -------------------------------------\
# ${0} outputDir ftpLink fileName            \
#--------------------------------------------\

OUTPUT_DIR=${1}
LINK=${2}
FILE_NAME=${3}


(set -x; directory-metadata; wget -O "$OUTPUT_DIR/$FILE_NAME" "$LINK/$FILE_NAME"; date -Imin) 2>&1 | tee "$OUTPUT_DIR/$FILE_NAME.log"
