#!/usr/bin/sh

# This script downloads a file with sequences from the PDB FTP archive
# and also creates a download log. Both files are saved at the specified path.

# Usage -------------------------------------\
# ${0} outputDir                             \
#--------------------------------------------\

OUTPUT_DIR=${1}

SEQ_LINK="https://files.wwpdb.org/pub/pdb/derived_data"
SEQ_FILE_NAME="pdb_seqres.txt.gz"


(set -x; directory-metadata; wget -O "$OUTPUT_DIR/$SEQ_FILE_NAME" "$SEQ_LINK/$SEQ_FILE_NAME"; date -Imin) 2>&1 | tee "$OUTPUT_DIR/$SEQ_FILE_NAME.log"
