#!/bin/perl

use strict;
use warnings;

my $idFile = $ARGV[0];
my $fastaFile = $ARGV[1];
my $outFile = $ARGV[2];

open(my $fasta_handler,'<', $fastaFile)
	or die " Could not open file: '$fastaFile' $!";
	
open(my $out_handler, '>', $outFile )
	or die "Could not open file '$outFile' $!";
	
open(my $id_handler,'<', $idFile)
	or die " Could not open file: '$idFile' $!";

my $id_line = <$id_handler>;
my @ids;
push(@ids, split(/,/, $id_line));
close($id_handler);


local $/ = "\n>";

my $current_seq='';
my $current_id='';
my $ref_line=<$fasta_handler>;
chomp $ref_line;
my $ref_id = $ids[0];
$ref_id = lc $ref_id;
$ref_line =~ /^(>$ref_id.+\n)([A-Z]+)/;
my $ref_seq = $2;
print $ref_seq;
my $index = 0;
while(my $line = <$fasta_handler>)
{
	my $id =  $ids[$index];
	$id = lc $id;
	$line =~ /^($id.+\n)([A-Z]+)\n/;
	$current_id = $id;
	$current_seq = $2;
	if( $current_id != $ref_id
		or  $current_seq != $ref_seq )
	{
		print $out_handler ">" . $1 . $current_seq . "\n";
		
	}
	print $2;
}
