#!/usr/bin/perl

use strict;
use warnings;
my $fastaFile = $ARGV[0];
my $outFile = $ARGV[1];


open(my $fasta_handler,'<', $fastaFile)
	or die " Could not open file: '$fastaFile' $!";

local $/=">";
my @good_lines;
my $ref_line= "";
my $ref_id='';
my $ref_seq='';
while(my $line = <$fasta_handler>)
{
	next if $line =~ /^#/;
	if($line =~ /^([a-z0-9]{4})_[A-Z].+\n([A-Z]+)\n/)
	{
		my $current_id = $1;
		my $current_seq = $2;
		if($ref_id eq $current_id)
		{
			if($ref_seq ne $current_seq)
			{
				$ref_seq = $current_seq;
				push @good_lines, $ref_line;
				$ref_line = $line;
			}
		}
		else
		{
			push @good_lines, $ref_line;
			$ref_id = $current_id;
			$ref_seq = $current_seq;
			$ref_line = $line;
		}
	}
}
$good_lines[0] = ">" . $good_lines[0];
chomp($good_lines[-1]);
open(my $out_handler, '>', $outFile )
	or die "Could not open file '$outFile' $!";

print $out_handler @good_lines;
close($out_handler);
close($fasta_handler);
