#!/bin/bash

input_file=$1
desired_clusters=$2
outdir=$3

for identity in $(seq 1.00 -0.01 0.70); do
    output_file="optimalClusters.fasta"
    echo "cd-hit -i $input_file -o $outdir/$output_file -c $identity"
    cd-hit -i "$input_file" -o "$outdir/$output_file" -c "$identity"

    num_clusters=$(grep -c '^>' "$outdir/$output_file")

    echo "Identity: $identity, Clusters, num: $num_clusters"

    if [[ "$num_clusters" -le "$desired_clusters" ]]; then
        echo "Found optimal identity for ($identity) for $desired_clusters cluseters"
        echo "Identity: $identity" > "$outdir/logs.log"
        echo "Desired_clusters_num: $desired_clusters" >> "$outdir/logs.log"
        echo "Real_clusters_num: $num_clusters" >> "$outdir/logs.log"
        break
       else
        rm "$outdir/$optimalClusters"
        rm "$outdir/$optimalClusters.clstr"
    fi
done
