#!/usr/bin/perl
use strict;
use warnings;

my $fastaFileName = $ARGV[0];
my $outDir = $ARGV[1];
open my $fh, '<', $fastaFileName or die "Could not open file: $!";


my $fastaNumber = 0;
while(my $header = <$fh>)
{
	my $output_file = "$outDir/fasta$fastaNumber.fasta";
	open(my $out, '>', $output_file) or die "Could not open file '$output_file': $!";
	
	chomp($header);
	my $seq = <$fh>;
	chomp($seq);
	print $out "$header\n$seq\n";
	
    	close($out);
    	$fastaNumber++;
}

close($fh);
